name: Compile Cart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  tic80version: '1.0'
  tic80release: '2164'
  scripttype: moon
  scriptextension: moon
  projectname: whitch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Clone Github Repo Action
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: nesbox
          repository: TIC-80
          
      - name: Git Submodules
        run: |
          cd TIC-80
          git submodule update --init --recursive
          
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install
        run: |
          sudo apt-get update
          sudo apt-get install libglu1-mesa-dev libasound2-dev libpulse-dev libaudio-dev libsamplerate0-dev -y
          
      - name: Build
        run: |
          cd TIC-80/build
          cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SDLGPU=On -DBUILD_PRO=On ..
          cmake --build . --config $BUILD_TYPE --parallel
          #cpack
          make -j4
          sudo make install
          
      #- name: release-downloader
      #  uses: robinraju/release-downloader@v1.7
      #  with:
      #    repository: nesbox/TIC-80
      #    tag: 'v${{ env.tic80version }}.${{ env.tic80release }}'
      #    fileName: '*.tar.gz'
      #    tarBall: true
      
      #- name: Extract release
      #  run: |
      #    tar -xf "TIC-80-v${{ env.tic80version }}.${{ env.tic80release }}.tar.gz"

      #- name: Make TIC-80
      #  run: |
      #    #cd nesbox-TIC-80-*
      #    cd TIC-80
      #    ls -al
      #    cmake .
      #    make -j4
      #    make install
          
      - name: Compile cart with TIC-80
        run: |
          ./tic80 --cli --fs . --cmd "load ${projectname:?}.${scriptextension:?} & mkdir dist & save dist/${projectname:?}"
      
      - name: Update Release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: './dist/${{ env.projectname }}.tic'
          message: 'A [TIC-80](https://tic80.com/) cart.'
          prerelease: true
          draft: true
